# --------
# Visualization only (relies on basic data and dist files to be generated by a jupyter notebook)
#
# Is about to be replaced by new draft_analysis.R
# --------

require(dplyr)
require(ggplot2)
require(tidyr)

myFolder <- "C:/Users/Sysadmin/Documents/draftsim/MTG-git/Arseny/" # There seems to be no good way to use relative addresses in R
setName <- 'DOM'

dist <- read.csv(file=paste(myFolder,"distances_",setName,".csv",sep=""), header=FALSE, sep=",")

ndim <- 2  # Number of dimensions ot use

fit <- cmdscale(dist,eig=TRUE, k=ndim) # Classical scaling

scale <- read.csv(file=paste(myFolder,"basic_data_",setName,".csv",sep=""), header=TRUE, sep=",")

if(ndim<3) {
  scale$x=fit$points[,1]
  scale$y=fit$points[,2]
} else {
  scale <- data.frame(x=fit$points[,1],y=fit$points[,2],z=fit$points[,3])
}
head(scale)

scale <- mutate(scale,color = factor(color,levels=c("C","W","U","B","R","G","Multi"))) # Put in a more meaningful order
scale <- filter(scale,freq>0)

### Output. Hidden for now, to preserve good files
# write.csv(scale,file = paste(myFolder,"R_output_",setName,".csv",sep=""),row.names=F)

myColors <- c("gray50","tan2","navyblue","black","red","green4","plum3")

# Clustering, only points
ggplot(scale) + theme_bw() + geom_point(aes(x,y,color=color)) +
  scale_color_manual(values=myColors) + xlab('') + ylab('') +
  theme(axis.text.x=element_blank(),         # Empty ticks, no gridlines
        axis.text.y=element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        axis.ticks = element_blank()
        )


# Points and labels
#install.packages("ggrepel")
require(ggrepel)
ggplot(scale) + theme_bw() + geom_point(aes(x,y,color=color)) +
  scale_color_manual(values=c("gray","tan2","blue","black","red","green","purple")) +
  geom_text_repel(aes(x,y,label=name),size=2,box.padding = 0.01, point.padding = 0.01) +
  xlab('') + ylab('') + 
  theme(axis.text.x=element_blank(),         # Empty ticks, no gridlines
        axis.text.y=element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        axis.ticks = element_blank()
  )

# Zoom in on the core (if necessary)
ggplot(scale) + theme_bw() + geom_point(aes(x,y,color=color)) +
  scale_color_manual(values=c("gray","tan2","blue","black","red","green","purple")) +
  geom_text_repel(aes(x,y,label=name),size=2,box.padding = 0.01, point.padding = 0.01) +
  xlim(-0.15,0.15) + ylim(-0.15,0.15)

# Rank
ggplot(scale) + theme_bw() + geom_point(aes(rank,Rating,color=color)) +
  scale_color_manual(values=myColors) +
  xlab("Draft point within a pack, 1 to 14") + ylab("Dan's rating")

temp <- scale
temp$r <- rank(temp$rank)
ggplot(temp,aes(Rating,r)) + theme_bw() + geom_point(aes(color=color)) +
  scale_color_manual(values=myColors) + ylab("Draft Rank") + xlab("Dan's rating") +
  geom_text(aes(label=name),size=2,hjust=-0.05) + xlim(0,6)

### ----------------------- 3d plot ---------
# (For it to work, scaling above shoudl be performed to 3D instead of 2D)
require(rgl)
require(car) # Applied regression
require(magick)

plot3d(scale$x,scale$y,scale$z,surface=F,col=myColors[scale$color],
       xlab="", ylab="", zlab="", size=4, alpha=0.8)
movie3d(spin3d(axis = c(0,0,1), rpm = 2), duration=10, type="gif", dir=myFolder)


# ----------- Guilds
gdf <- data.frame(guilds)
colorVector <- c("W","U","B","R","G")
gdf$c1 <- 1:5
gdf2 <- gather(gdf,c2,val,-c1) 
gdf2 <- gdf2 %>% mutate(c2 = factor(c2,labels=colorVector), c1 = factor(c1,labels=colorVector))
guilds

ggplot(data=gdf2,aes(c1,c2,fill=val)) + theme_bw() + geom_tile() +
  scale_fill_gradient2(low="navy", mid="white", high="red") +
  geom_text(aes(c1,c2,label=sprintf("%2d%%",round(100*val))),color="brown") +
  xlab('Color 1') + ylab('Color 2') + guides(fill=F)


# ----------- Color history
histData <- NULL
histData <- data.frame()
binLength <- 1000
for(i in 1:floor(length(colorHist)/binLength)){
  h <- hist(colorHist[(1+(i-1)*binLength):(i*binLength)],c(1:6)-0.5)
  histData <- rbind(histData,data.frame(t=i,
      w=h$density[1],u=h$density[2],b=h$density[3],r=h$density[4],g=h$density[5]))
}
histData2 <- gather(histData,Color,Value,-t)
histData2$Color <- factor(histData2$Color,levels=c('w','u','b','r','g'))
myColors2 <- c("tan2","blue","black","red",muted("green"),"purple")
ggplot(data=histData2,aes(t,Value,fill=Color)) + theme_bw() +
  scale_fill_manual(values=myColors2) +
  geom_area(alpha=0.8) + 
  xlab('Thousands of drafts into the guild') + ylab('Share as a 1st color')
require(scales)
ggplot(data=histData2,aes(t,Value,color=Color)) + theme_bw() +
  geom_point(alpha=0.3) + geom_smooth(method=lm,se=F) +
  scale_color_manual(values=myColors2) +
  facet_grid(.~Color) + 
  xlab('Thousands of drafts') + ylab('Share as a 1st color')


# ------------- Save results
write.table(scale, file = "C:/Users/Sysadmin/Documents/draftsim/out.csv", sep = ",",col.names = NA, qmethod = "double")
write.table(dist, file = "C:/Users/Sysadmin/Documents/draftsim/dist.csv", sep = ",",
            col.names = F, row.names=F, qmethod = "double")
write.table(prefs, file = "C:/Users/Sysadmin/Documents/draftsim/prefs.csv", sep = ",",
            col.names = F, row.names=F, qmethod = "double")


# ----------------------------------------------------------------------
# ------------- Comparisons of earlier and later drafts (relies on pre-saved files)
# To run it, either recalculate the scales, or save some somewhere once and for all

load("C:/Users/Sysadmin/Documents/draftsim/pairs variable M19 part 1 v3.RData")
# Now run everything above
scale1 <- scale # First analyze one set, do this
guilds1 <- guilds

load("C:/Users/Sysadmin/Documents/draftsim/pairs variable M19 part 2 v3.RData")
# Run stuff above
scale2 <- scale # Then repeat with another set, and do this
guilds2 <- guilds

# General prepping
scale1 <- rename(scale1,x1=x,y1=y,z1=z,rank1=rank)
scale2 <- rename(scale2,x2=x,y2=y,z2=z,rank2=rank)
names(scale1)
names(scale2)
full <- inner_join(scale1,dplyr::select(scale2,id,x2,y2,z2,rank2),by="id") #
names(full)
modelx <- lm(data=full,x2~x1+y1+z1) # Best way to transform xy into x2y2
modely <- lm(data=full,y2~x1+y1+z1)
modelz <- lm(data=full,z2~x1+y1+z1)
full$x1 <- fitted(modelx) # So now try to transform xy towards x2y2.  
full$y1 <- fitted(modely) # You'll get x1y1 that are comparable with x2y2 (rotated similarly)
full$z1 <- fitted(modelz)
full <- select(full,id,name,color,Rating,rank1,rank2,x1,y1,x2,y2)
names(full)

# Sense-check: do we reproduce old scatters? (yes)
ggplot(full) + theme_bw() + geom_point(aes(x1,y1,color=color)) + scale_color_manual(values=myColors)
ggplot(full) + theme_bw() + geom_point(aes(x2,y2,color=color)) + scale_color_manual(values=myColors)
head(full)

# Combine both
full2 <- gather(full, key = stage, value=x, -id, -name, -color, -Rating, -rank1,-rank2, -y1, -y2) # Combine old and new
full2$y <- ifelse(full2$stage=="x1",full2$y1,full2$y2) # Take appropriate y
full2$rank <- ifelse(full2$stage=="x1",full2$rank1,full2$rank2)
full2 <- full2 %>% mutate(stage=factor(stage,labels=c("Jul","Aug")))
names(full2)
head(full2)

freq2 <- data.frame(freq=freq)
freq2$id <- 1:nrow(freq2)
full2 <- inner_join(full2,freq2,by="id")
names(full2)

# Flocks
ggplot(full2,aes(x,y,color=color,shape=stage,group=id)) + theme_bw() + geom_point() + 
  geom_line() + scale_color_manual(values=myColors) + scale_shape_manual(values=c(20,15)) +
  xlab('') + ylab('')

# Flocks with labels
ggplot(full2,aes(x,y,color=color,shape=stage,group=id)) + theme_bw() + geom_point() + 
  geom_line() + scale_color_manual(values=myColors) + scale_shape_manual(values=c(20,15)) +
  xlab('') + ylab('') +
  geom_text_repel(data=subset(full2,stage=="Aug"),aes(x,y,label=name),
                  size=2,box.padding = 0.01, point.padding = 0.01,color="black")

# Guilds
guildChange <- guilds2-guilds1
gdf <- data.frame(guildChange)
colorVector <- c("W","U","B","R","G")
gdf$c1 <- 1:5
gdf2 <- gather(gdf,c2,val,-c1) 
gdf2 <- gdf2 %>% mutate(c2 = factor(c2,labels=colorVector), c1 = factor(c1,labels=colorVector))
guildChange

ggplot(data=gdf2,aes(c1,c2,fill=val)) + theme_bw() + geom_tile() +
  scale_fill_gradient2(low="navy", mid="white", high="red") +
  scale_color_gradient2(low="black", mid="gray", high="brown") +
  geom_text(aes(c1,c2,label=sprintf("%2d%%",round(100*val)),color=val)) +
  xlab('Color 1') + ylab('Color 2') + guides(fill=F,color=F)


# Ranks. First - via correlation
ggplot(full,aes(rank1,rank2,color=color)) + theme_bw() + geom_point() + 
  scale_color_manual(values=myColors) + xlab("Pick # within a booster, July") + ylab("Pick within a booster, August")

#ggplot(full,aes(rank1,rank2,color=color)) + theme_bw() + geom_point() + 
#  scale_color_manual(values=myColors) + xlab("Pick # within booster, July") + ylab("Pick within booster, August") +
#  geom_text_repel(aes(label=name),size=2,box.padding = 0.01, point.padding = 0.01,color="black")

# What color lost in pick order in ranks the most? Black.
ggplot(full,aes(color,rank2-rank1,color=color)) + theme_bw() + geom_point() +
  scale_color_manual(values=myColors) +
  stat_summary(fun.y="mean",color="black",shape=22,size=3,geom="point") +
  ylab("Pick order, Aug - July") + guides(color=F)

ggplot(full2,aes(stage,rank,color=color)) + theme_bw() + geom_point() +
  scale_color_manual(values=myColors) + guides(color=F) +
  facet_grid(.~color) + geom_line(aes(group=id),alpha=0.5)

# Canceling color effect
m <- lm(data=full2,rank2~rank1+color) # Estimate shift of rank2 compared to rank1 by color
full2$rank2prime <- full$rank2-(fitted(m)-full$rank1) # Subtract these shifts from rank2
#ggplot(full2,aes(rank2,rank2prime,color=color)) + geom_point() + theme_bw() +
#  scale_color_manual(values=myColors)

if(1){ # Set to 1 to cancel color effect
  full2sub <- subset(full2,abs(rank2prime-rank1)>quantile(abs(rank2prime-rank1),0.75))
  full2sub$rank2 <- full2sub$rank2prime # Give up, just overwrite old rank2 with the new one
}else{
  full2sub <- subset(full2,abs(rank2prime-rank1)>quantile(abs(rank2-rank1),0.75))
}
full2sub$rank1 <- rank(full2sub$rank1)
full2sub$rank2 <- rank(full2sub$rank2)
full2sub$rank <- ifelse(full2sub$stage=="Jul",full2sub$rank1,full2sub$rank2) # Take appropriate rank

# Optimal combo
ggplot(full2sub,aes(stage,125-rank,group=id)) + theme_bw()  + 
  geom_line(aes(color=(rank2<rank1),alpha=abs(rank2-rank))) + 
  geom_point() +
  scale_color_manual(values=c("0"="gray60","W"="gold4","U"=myColors[3],"B"=myColors[4],
                              "R"="red3","G"=myColors[6],"M"=myColors[7],
                              "FALSE"="deepskyblue","TRUE"="red3")) +
  geom_text(aes("Aug",125-rank2,label=name,color=color),size=2,hjust="left",position = position_nudge(x = 0.05)) +
  guides(color=F,alpha=F) + ylab("Ranked card score (higher is better)")
    